default: &default
  adapter: postgresql
  url:  <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>

production:
  <<: *default
development:
  <<: *default
test:
  <<: *default
